var GAME_LEVELS = [
  ["                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                             p                                               ",
   "                                            yyy                                              ",
   "                                                                                             ",
   "                                        x!!!!!!!!!x                                          ",
   "                                      xxxx!!!!!!!xxxxx                                       ",
   "                               o    xxxxxxx!!!!!xxxxxxxx    o                                ",
   "                              xxx           !!!            xxx                               ",
   "                          p                 !!!                   p                          ",
   "                        yyyy                !!!                  yyyy                        ",
   "                                            !!!                                              ",
   "                 o                          !!!                         o                    ",
   "               xxxxx                        !!!                       xxxxx                  ",
   "                                            !!!                                              ",
   "    @                                       !!!                                              ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx             !!!            xxxxxxxxxxxxxxxxxxxxxxxx     xxxx ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x     x    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x  o  x    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x     x    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      x     x    "],






   ["                                                                                             ",
    "                                                                            @                ",
    "                                                                                             ",
    "                                                                                             ",
    "                                                                                             ",
    "                                                                                             ",
    "                                                                                             ",
    "  =             xxx                                                         xxx          =   ",
    "                                                                                             ",
    "  =                         yyy            yyy                         yyy               =   ",
    "                                                                                             ",
    "  =                                                  xxx                                 =   ",
    "               xxx                                                                           ",
    "                            yyy                           yyy                                ",
    "  =                                                                                      =   ",
    "                    xxx              xxx                           xxx                       ",
    "                                                                                             ",
    "        yyy                                  xxx                                             ",
    "                                   yyy                                                    p  ",
    "                                                                                         yyy ",
    "!!x     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!x  o  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!x     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],


    ["       x  !!!        !!!           !!!!!        !!!              !                            ",
     "   @   x  !!!        !!!           !!!!!        !!!              !                            ",
     "       x  !!!        !!!           !!!!!        v v              v                            ",
     "       x   v         !!!           !!!!!                                                      ",
     "       x              v            v v v                                                      ",
     "b      x                                                             x!!       !!x            ",
     "y      x                                                            yx!!       !!x            ",
     "       x                                                             x!!       !!x            ",
     "       x                                                      y      x!!       !!x            ",
     "       x                      o             o                        x!!       !!x            ",
     "       x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             yx!!       !!x            ",
     "       x       xxxx      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              x!!       !!x            ",
     "       x      yx  x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       y      x!!       !!x            ",
     "       x       x  xy     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              x!!       !!x            ",
     "       x       x  x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x             yx!!       !!x            ",
     "       xy      x  x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              x!!       !!x            ",
     "       x       x  x    y x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              x!!       !!x            ",
     "       x       x  x          v      v      v       v          y      x!!       !!x            ",
     "       x      yx  x                                                  x!!       !!x            ",
     "       x       x  xy                                                 x!!       !!x            ",
     "               x  x                                                 yx!!   o   !!x            ",
     "               x  x             o       o       o                    x!!       !!x            ",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!       !!xxxxxxxxxxxxx",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!       !!xxxxxxxxxxxxx",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!       !!xxxxxxxxxxxxx",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!       !!xxxxxxxxxxxxx",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "           p   p  p p p  p   p   p       p       p p pp     p                                 ",
     "            p p   p   p  p   p    p     p p     p  p p p    p                                 ",
     "             p    p   p  p   p     p   p   p   p   p p  p   p                                 ",
     "             p    p   p  p   p      p p     p p    p p   p  p                                 ",
     "             p    p p p  p p p       p       p     p p    p p                                 ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "                                                                                              ",
     "  o                                                                                           ",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],






 ];
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
